# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='platform.proto',
  package='org.dash.platform.dapi.v0',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eplatform.proto\x12\x19org.dash.platform.dapi.v0\"7\n\x1b\x41pplyStateTransitionRequest\x12\x18\n\x10state_transition\x18\x01 \x01(\x0c\"\x1e\n\x1c\x41pplyStateTransitionResponse\" \n\x12GetIdentityRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x13GetIdentityResponse\x12\x10\n\x08identity\x18\x01 \x01(\x0c\"$\n\x16GetDataContractRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x17GetDataContractResponse\x12\x15\n\rdata_contract\x18\x01 \x01(\x0c\"\xaa\x01\n\x13GetDocumentsRequest\x12\x18\n\x10\x64\x61ta_contract_id\x18\x01 \x01(\t\x12\x15\n\rdocument_type\x18\x02 \x01(\t\x12\r\n\x05where\x18\x03 \x01(\x0c\x12\x10\n\x08order_by\x18\x04 \x01(\x0c\x12\r\n\x05limit\x18\x05 \x01(\r\x12\x15\n\x0bstart_after\x18\x06 \x01(\rH\x00\x12\x12\n\x08start_at\x18\x07 \x01(\rH\x00\x42\x07\n\x05start\")\n\x14GetDocumentsResponse\x12\x11\n\tdocuments\x18\x01 \x03(\x0c\x32\xed\x03\n\x08Platform\x12\x87\x01\n\x14\x61pplyStateTransition\x12\x36.org.dash.platform.dapi.v0.ApplyStateTransitionRequest\x1a\x37.org.dash.platform.dapi.v0.ApplyStateTransitionResponse\x12l\n\x0bgetIdentity\x12-.org.dash.platform.dapi.v0.GetIdentityRequest\x1a..org.dash.platform.dapi.v0.GetIdentityResponse\x12x\n\x0fgetDataContract\x12\x31.org.dash.platform.dapi.v0.GetDataContractRequest\x1a\x32.org.dash.platform.dapi.v0.GetDataContractResponse\x12o\n\x0cgetDocuments\x12..org.dash.platform.dapi.v0.GetDocumentsRequest\x1a/.org.dash.platform.dapi.v0.GetDocumentsResponseb\x06proto3')
)




_APPLYSTATETRANSITIONREQUEST = _descriptor.Descriptor(
  name='ApplyStateTransitionRequest',
  full_name='org.dash.platform.dapi.v0.ApplyStateTransitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_transition', full_name='org.dash.platform.dapi.v0.ApplyStateTransitionRequest.state_transition', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=100,
)


_APPLYSTATETRANSITIONRESPONSE = _descriptor.Descriptor(
  name='ApplyStateTransitionResponse',
  full_name='org.dash.platform.dapi.v0.ApplyStateTransitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=132,
)


_GETIDENTITYREQUEST = _descriptor.Descriptor(
  name='GetIdentityRequest',
  full_name='org.dash.platform.dapi.v0.GetIdentityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.dash.platform.dapi.v0.GetIdentityRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=166,
)


_GETIDENTITYRESPONSE = _descriptor.Descriptor(
  name='GetIdentityResponse',
  full_name='org.dash.platform.dapi.v0.GetIdentityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='org.dash.platform.dapi.v0.GetIdentityResponse.identity', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=207,
)


_GETDATACONTRACTREQUEST = _descriptor.Descriptor(
  name='GetDataContractRequest',
  full_name='org.dash.platform.dapi.v0.GetDataContractRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.dash.platform.dapi.v0.GetDataContractRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=245,
)


_GETDATACONTRACTRESPONSE = _descriptor.Descriptor(
  name='GetDataContractResponse',
  full_name='org.dash.platform.dapi.v0.GetDataContractResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_contract', full_name='org.dash.platform.dapi.v0.GetDataContractResponse.data_contract', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=295,
)


_GETDOCUMENTSREQUEST = _descriptor.Descriptor(
  name='GetDocumentsRequest',
  full_name='org.dash.platform.dapi.v0.GetDocumentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_contract_id', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.data_contract_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='document_type', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.document_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='where', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.where', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_by', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.order_by', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.limit', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_after', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.start_after', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_at', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.start_at', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='start', full_name='org.dash.platform.dapi.v0.GetDocumentsRequest.start',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=298,
  serialized_end=468,
)


_GETDOCUMENTSRESPONSE = _descriptor.Descriptor(
  name='GetDocumentsResponse',
  full_name='org.dash.platform.dapi.v0.GetDocumentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='documents', full_name='org.dash.platform.dapi.v0.GetDocumentsResponse.documents', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=511,
)

_GETDOCUMENTSREQUEST.oneofs_by_name['start'].fields.append(
  _GETDOCUMENTSREQUEST.fields_by_name['start_after'])
_GETDOCUMENTSREQUEST.fields_by_name['start_after'].containing_oneof = _GETDOCUMENTSREQUEST.oneofs_by_name['start']
_GETDOCUMENTSREQUEST.oneofs_by_name['start'].fields.append(
  _GETDOCUMENTSREQUEST.fields_by_name['start_at'])
_GETDOCUMENTSREQUEST.fields_by_name['start_at'].containing_oneof = _GETDOCUMENTSREQUEST.oneofs_by_name['start']
DESCRIPTOR.message_types_by_name['ApplyStateTransitionRequest'] = _APPLYSTATETRANSITIONREQUEST
DESCRIPTOR.message_types_by_name['ApplyStateTransitionResponse'] = _APPLYSTATETRANSITIONRESPONSE
DESCRIPTOR.message_types_by_name['GetIdentityRequest'] = _GETIDENTITYREQUEST
DESCRIPTOR.message_types_by_name['GetIdentityResponse'] = _GETIDENTITYRESPONSE
DESCRIPTOR.message_types_by_name['GetDataContractRequest'] = _GETDATACONTRACTREQUEST
DESCRIPTOR.message_types_by_name['GetDataContractResponse'] = _GETDATACONTRACTRESPONSE
DESCRIPTOR.message_types_by_name['GetDocumentsRequest'] = _GETDOCUMENTSREQUEST
DESCRIPTOR.message_types_by_name['GetDocumentsResponse'] = _GETDOCUMENTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApplyStateTransitionRequest = _reflection.GeneratedProtocolMessageType('ApplyStateTransitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLYSTATETRANSITIONREQUEST,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.ApplyStateTransitionRequest)
  })
_sym_db.RegisterMessage(ApplyStateTransitionRequest)

ApplyStateTransitionResponse = _reflection.GeneratedProtocolMessageType('ApplyStateTransitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPLYSTATETRANSITIONRESPONSE,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.ApplyStateTransitionResponse)
  })
_sym_db.RegisterMessage(ApplyStateTransitionResponse)

GetIdentityRequest = _reflection.GeneratedProtocolMessageType('GetIdentityRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETIDENTITYREQUEST,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.GetIdentityRequest)
  })
_sym_db.RegisterMessage(GetIdentityRequest)

GetIdentityResponse = _reflection.GeneratedProtocolMessageType('GetIdentityResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETIDENTITYRESPONSE,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.GetIdentityResponse)
  })
_sym_db.RegisterMessage(GetIdentityResponse)

GetDataContractRequest = _reflection.GeneratedProtocolMessageType('GetDataContractRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDATACONTRACTREQUEST,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.GetDataContractRequest)
  })
_sym_db.RegisterMessage(GetDataContractRequest)

GetDataContractResponse = _reflection.GeneratedProtocolMessageType('GetDataContractResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDATACONTRACTRESPONSE,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.GetDataContractResponse)
  })
_sym_db.RegisterMessage(GetDataContractResponse)

GetDocumentsRequest = _reflection.GeneratedProtocolMessageType('GetDocumentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDOCUMENTSREQUEST,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.GetDocumentsRequest)
  })
_sym_db.RegisterMessage(GetDocumentsRequest)

GetDocumentsResponse = _reflection.GeneratedProtocolMessageType('GetDocumentsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDOCUMENTSRESPONSE,
  '__module__' : 'platform_pb2'
  # @@protoc_insertion_point(class_scope:org.dash.platform.dapi.v0.GetDocumentsResponse)
  })
_sym_db.RegisterMessage(GetDocumentsResponse)



_PLATFORM = _descriptor.ServiceDescriptor(
  name='Platform',
  full_name='org.dash.platform.dapi.v0.Platform',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=514,
  serialized_end=1007,
  methods=[
  _descriptor.MethodDescriptor(
    name='applyStateTransition',
    full_name='org.dash.platform.dapi.v0.Platform.applyStateTransition',
    index=0,
    containing_service=None,
    input_type=_APPLYSTATETRANSITIONREQUEST,
    output_type=_APPLYSTATETRANSITIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getIdentity',
    full_name='org.dash.platform.dapi.v0.Platform.getIdentity',
    index=1,
    containing_service=None,
    input_type=_GETIDENTITYREQUEST,
    output_type=_GETIDENTITYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getDataContract',
    full_name='org.dash.platform.dapi.v0.Platform.getDataContract',
    index=2,
    containing_service=None,
    input_type=_GETDATACONTRACTREQUEST,
    output_type=_GETDATACONTRACTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getDocuments',
    full_name='org.dash.platform.dapi.v0.Platform.getDocuments',
    index=3,
    containing_service=None,
    input_type=_GETDOCUMENTSREQUEST,
    output_type=_GETDOCUMENTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLATFORM)

DESCRIPTOR.services_by_name['Platform'] = _PLATFORM

# @@protoc_insertion_point(module_scope)
